// =====================================================================
//  TURKIYE 81 IL VERISI  —  ortak veri dosyasi
// ---------------------------------------------------------------------
//  RECODE NOTU: Bu liste tum sayfalarda kullaniliyor. Guzel bir sey!
//  Ama ilce verisi cok eksik (sadece birkac il icin var).
//  Iyilestirme: her ile ilce listesi ekle, koordinat ekle, harita bagla.
// =====================================================================

var ILLER = [
  {plaka:1,  ad:"Adana",          bolge:"Akdeniz",              ilceler:["Seyhan","Çukurova","Ceyhan","Kozan","Yüreğir"]},
  {plaka:2,  ad:"Adıyaman",       bolge:"Güneydoğu Anadolu",    ilceler:["Merkez","Kahta","Besni"]},
  {plaka:3,  ad:"Afyonkarahisar", bolge:"Ege",                  ilceler:["Merkez","Sandıklı","Dinar"]},
  {plaka:4,  ad:"Ağrı",           bolge:"Doğu Anadolu",         ilceler:["Merkez","Doğubayazıt","Patnos"]},
  {plaka:5,  ad:"Amasya",         bolge:"Karadeniz",            ilceler:["Merkez","Merzifon","Suluova"]},
  {plaka:6,  ad:"Ankara",         bolge:"İç Anadolu",           ilceler:["Çankaya","Keçiören","Yenimahalle","Mamak","Etimesgut"]},
  {plaka:7,  ad:"Antalya",        bolge:"Akdeniz",              ilceler:["Muratpaşa","Kepez","Alanya","Manavgat","Konyaaltı"]},
  {plaka:8,  ad:"Artvin",         bolge:"Karadeniz",            ilceler:["Merkez","Hopa","Borçka"]},
  {plaka:9,  ad:"Aydın",          bolge:"Ege",                  ilceler:["Efeler","Nazilli","Söke","Kuşadası"]},
  {plaka:10, ad:"Balıkesir",      bolge:"Marmara",              ilceler:["Karesi","Altıeylül","Bandırma","Edremit"]},
  {plaka:11, ad:"Bilecik",        bolge:"Marmara",              ilceler:["Merkez","Bozüyük","Söğüt"]},
  {plaka:12, ad:"Bingöl",         bolge:"Doğu Anadolu",         ilceler:["Merkez","Genç","Solhan"]},
  {plaka:13, ad:"Bitlis",         bolge:"Doğu Anadolu",         ilceler:["Merkez","Tatvan","Ahlat"]},
  {plaka:14, ad:"Bolu",           bolge:"Karadeniz",            ilceler:["Merkez","Gerede","Mudurnu"]},
  {plaka:15, ad:"Burdur",         bolge:"Akdeniz",              ilceler:["Merkez","Bucak","Gölhisar"]},
  {plaka:16, ad:"Bursa",          bolge:"Marmara",              ilceler:["Osmangazi","Nilüfer","Yıldırım","İnegöl","Gemlik"]},
  {plaka:17, ad:"Çanakkale",      bolge:"Marmara",              ilceler:["Merkez","Biga","Çan","Gelibolu"]},
  {plaka:18, ad:"Çankırı",        bolge:"İç Anadolu",           ilceler:["Merkez","Çerkeş","Ilgaz"]},
  {plaka:19, ad:"Çorum",          bolge:"Karadeniz",            ilceler:["Merkez","Sungurlu","Osmancık"]},
  {plaka:20, ad:"Denizli",        bolge:"Ege",                  ilceler:["Pamukkale","Merkezefendi","Çivril"]},
  {plaka:21, ad:"Diyarbakır",     bolge:"Güneydoğu Anadolu",    ilceler:["Bağlar","Kayapınar","Yenişehir","Bismil"]},
  {plaka:22, ad:"Edirne",         bolge:"Marmara",              ilceler:["Merkez","Keşan","Uzunköprü"]},
  {plaka:23, ad:"Elazığ",         bolge:"Doğu Anadolu",         ilceler:["Merkez","Kovancılar","Karakoçan"]},
  {plaka:24, ad:"Erzincan",       bolge:"Doğu Anadolu",         ilceler:["Merkez","Tercan","Üzümlü"]},
  {plaka:25, ad:"Erzurum",        bolge:"Doğu Anadolu",         ilceler:["Yakutiye","Palandöken","Aziziye","Oltu"]},
  {plaka:26, ad:"Eskişehir",      bolge:"İç Anadolu",           ilceler:["Odunpazarı","Tepebaşı","Sivrihisar"]},
  {plaka:27, ad:"Gaziantep",      bolge:"Güneydoğu Anadolu",    ilceler:["Şahinbey","Şehitkamil","Nizip"]},
  {plaka:28, ad:"Giresun",        bolge:"Karadeniz",            ilceler:["Merkez","Bulancak","Espiye"]},
  {plaka:29, ad:"Gümüşhane",      bolge:"Karadeniz",            ilceler:["Merkez","Kelkit","Şiran"]},
  {plaka:30, ad:"Hakkari",        bolge:"Doğu Anadolu",         ilceler:["Merkez","Yüksekova","Şemdinli"]},
  {plaka:31, ad:"Hatay",          bolge:"Akdeniz",              ilceler:["Antakya","İskenderun","Defne","Dörtyol"]},
  {plaka:32, ad:"Isparta",        bolge:"Akdeniz",              ilceler:["Merkez","Yalvaç","Eğirdir"]},
  {plaka:33, ad:"Mersin",         bolge:"Akdeniz",              ilceler:["Akdeniz","Toroslar","Yenişehir","Tarsus","Mezitli"]},
  {plaka:34, ad:"İstanbul",       bolge:"Marmara",              ilceler:["Kadıköy","Beşiktaş","Üsküdar","Fatih","Beyoğlu","Şişli","Bakırköy"]},
  {plaka:35, ad:"İzmir",          bolge:"Ege",                  ilceler:["Konak","Karşıyaka","Bornova","Buca","Çeşme","Alsancak"]},
  {plaka:36, ad:"Kars",           bolge:"Doğu Anadolu",         ilceler:["Merkez","Sarıkamış","Kağızman"]},
  {plaka:37, ad:"Kastamonu",      bolge:"Karadeniz",            ilceler:["Merkez","Tosya","Taşköprü"]},
  {plaka:38, ad:"Kayseri",        bolge:"İç Anadolu",           ilceler:["Melikgazi","Kocasinan","Talas"]},
  {plaka:39, ad:"Kırklareli",     bolge:"Marmara",              ilceler:["Merkez","Lüleburgaz","Babaeski"]},
  {plaka:40, ad:"Kırşehir",       bolge:"İç Anadolu",           ilceler:["Merkez","Kaman","Mucur"]},
  {plaka:41, ad:"Kocaeli",        bolge:"Marmara",              ilceler:["İzmit","Gebze","Darıca","Körfez"]},
  {plaka:42, ad:"Konya",          bolge:"İç Anadolu",           ilceler:["Selçuklu","Meram","Karatay","Ereğli"]},
  {plaka:43, ad:"Kütahya",        bolge:"Ege",                  ilceler:["Merkez","Tavşanlı","Simav"]},
  {plaka:44, ad:"Malatya",        bolge:"Doğu Anadolu",         ilceler:["Battalgazi","Yeşilyurt","Doğanşehir"]},
  {plaka:45, ad:"Manisa",         bolge:"Ege",                  ilceler:["Şehzadeler","Yunusemre","Akhisar","Salihli"]},
  {plaka:46, ad:"Kahramanmaraş",  bolge:"Akdeniz",              ilceler:["Onikişubat","Dulkadiroğlu","Elbistan"]},
  {plaka:47, ad:"Mardin",         bolge:"Güneydoğu Anadolu",    ilceler:["Artuklu","Kızıltepe","Midyat"]},
  {plaka:48, ad:"Muğla",          bolge:"Ege",                  ilceler:["Menteşe","Bodrum","Fethiye","Marmaris","Milas"]},
  {plaka:49, ad:"Muş",            bolge:"Doğu Anadolu",         ilceler:["Merkez","Bulanık","Malazgirt"]},
  {plaka:50, ad:"Nevşehir",       bolge:"İç Anadolu",           ilceler:["Merkez","Ürgüp","Avanos"]},
  {plaka:51, ad:"Niğde",          bolge:"İç Anadolu",           ilceler:["Merkez","Bor","Çamardı"]},
  {plaka:52, ad:"Ordu",           bolge:"Karadeniz",            ilceler:["Altınordu","Ünye","Fatsa"]},
  {plaka:53, ad:"Rize",           bolge:"Karadeniz",            ilceler:["Merkez","Çayeli","Ardeşen","Pazar"]},
  {plaka:54, ad:"Sakarya",        bolge:"Marmara",              ilceler:["Adapazarı","Serdivan","Erenler"]},
  {plaka:55, ad:"Samsun",         bolge:"Karadeniz",            ilceler:["İlkadım","Atakum","Canik","Bafra"]},
  {plaka:56, ad:"Siirt",          bolge:"Güneydoğu Anadolu",    ilceler:["Merkez","Kurtalan","Pervari"]},
  {plaka:57, ad:"Sinop",          bolge:"Karadeniz",            ilceler:["Merkez","Boyabat","Gerze"]},
  {plaka:58, ad:"Sivas",          bolge:"İç Anadolu",           ilceler:["Merkez","Şarkışla","Suşehri"]},
  {plaka:59, ad:"Tekirdağ",       bolge:"Marmara",              ilceler:["Süleymanpaşa","Çorlu","Çerkezköy"]},
  {plaka:60, ad:"Tokat",          bolge:"Karadeniz",            ilceler:["Merkez","Erbaa","Turhal"]},
  {plaka:61, ad:"Trabzon",        bolge:"Karadeniz",            ilceler:["Ortahisar","Akçaabat","Of","Araklı"]},
  {plaka:62, ad:"Tunceli",        bolge:"Doğu Anadolu",         ilceler:["Merkez","Pertek","Mazgirt"]},
  {plaka:63, ad:"Şanlıurfa",      bolge:"Güneydoğu Anadolu",    ilceler:["Eyyübiye","Haliliye","Karaköprü","Siverek"]},
  {plaka:64, ad:"Uşak",           bolge:"Ege",                  ilceler:["Merkez","Banaz","Eşme"]},
  {plaka:65, ad:"Van",            bolge:"Doğu Anadolu",         ilceler:["İpekyolu","Tuşba","Erciş","Edremit"]},
  {plaka:66, ad:"Yozgat",         bolge:"İç Anadolu",           ilceler:["Merkez","Sorgun","Akdağmadeni"]},
  {plaka:67, ad:"Zonguldak",      bolge:"Karadeniz",            ilceler:["Merkez","Ereğli","Çaycuma"]},
  {plaka:68, ad:"Aksaray",        bolge:"İç Anadolu",           ilceler:["Merkez","Ortaköy","Eskil"]},
  {plaka:69, ad:"Bayburt",        bolge:"Karadeniz",            ilceler:["Merkez","Demirözü","Aydıntepe"]},
  {plaka:70, ad:"Karaman",        bolge:"İç Anadolu",           ilceler:["Merkez","Ermenek","Sarıveliler"]},
  {plaka:71, ad:"Kırıkkale",      bolge:"İç Anadolu",           ilceler:["Merkez","Yahşihan","Keskin"]},
  {plaka:72, ad:"Batman",         bolge:"Güneydoğu Anadolu",    ilceler:["Merkez","Kozluk","Sason"]},
  {plaka:73, ad:"Şırnak",         bolge:"Güneydoğu Anadolu",    ilceler:["Merkez","Cizre","Silopi","İdil"]},
  {plaka:74, ad:"Bartın",         bolge:"Karadeniz",            ilceler:["Merkez","Amasra","Ulus"]},
  {plaka:75, ad:"Ardahan",        bolge:"Doğu Anadolu",         ilceler:["Merkez","Göle","Çıldır"]},
  {plaka:76, ad:"Iğdır",          bolge:"Doğu Anadolu",         ilceler:["Merkez","Tuzluca","Aralık"]},
  {plaka:77, ad:"Yalova",         bolge:"Marmara",              ilceler:["Merkez","Çınarcık","Termal"]},
  {plaka:78, ad:"Karabük",        bolge:"Karadeniz",            ilceler:["Merkez","Safranbolu","Yenice"]},
  {plaka:79, ad:"Kilis",          bolge:"Güneydoğu Anadolu",    ilceler:["Merkez","Musabeyli","Polateli"]},
  {plaka:80, ad:"Osmaniye",       bolge:"Akdeniz",              ilceler:["Merkez","Kadirli","Düziçi"]},
  {plaka:81, ad:"Düzce",          bolge:"Karadeniz",            ilceler:["Merkez","Akçakoca","Gölyaka"]}
];

// bolge renkleri (RECODE: bunlari CSS'e tasiyabilirsin)
var BOLGE_RENK = {
  "Marmara":"#5b8def",
  "Ege":"#d4af37",
  "Akdeniz":"#e0704a",
  "İç Anadolu":"#c9a05c",
  "Karadeniz":"#4ac06a",
  "Doğu Anadolu":"#9b6bd8",
  "Güneydoğu Anadolu":"#e04872"
};
